server:
  port: 80

spring:
  application:
    name: xyc-order
  cloud:
    nacos:
      discovery:
        server-addr: 47.116.216.209:8848
      config:
        group: DEFAULT_GROUP
        server-addr: 47.116.216.209:8848
      loadbalancer:
        ribbon:
          enabled: false
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
  config:
    import: nacos:xyc-order.yaml
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 47.116.216.209:8848
      application: seata-server
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: 47.116.216.209:8848
      group: SEATA_GROUP
      data-id: seataServer.properties
